//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Runtime/Scripts/Comps/Inputs/Actions/RayNeoInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RayNeoInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RayNeoInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RayNeoInput"",
    ""maps"": [
        {
            ""name"": ""SimpleTouch"",
            ""id"": ""3ee82658-13e9-43a1-b803-5c00561e5f49"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""f65f1bc0-5c7c-4d25-ae46-f4ead2976053"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7d789459-0fa4-4d1e-b14d-6a2885d3252a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""PassThrough"",
                    ""id"": ""46cc4698-f59d-4059-bb8e-9c201ad1ffae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29130e4c-b31c-4a56-b73a-096bbf7c1465"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4fb838e-cafc-48b5-a432-40ac4e7124cd"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4537a551-5f67-4c59-9af4-39f5e22c4d32"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a3cfdba-4b0a-46fe-8ae9-8af1ee59d297"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""786c51c8-605f-48d5-b9d7-cf09f1a41335"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72efd082-c0a5-4374-b7dd-8f51c71c2cd3"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MulitTouch"",
            ""id"": ""af95e208-2af8-4d85-9f62-874579f250d7"",
            ""actions"": [
                {
                    ""name"": ""Touch1Tap"",
                    ""type"": ""Button"",
                    ""id"": ""06fa4ec7-69ab-4248-abb6-7ca41bdb441a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch2Tap"",
                    ""type"": ""Button"",
                    ""id"": ""3b56ea4f-927c-441e-ae4b-824df2788a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch1Position"",
                    ""type"": ""Value"",
                    ""id"": ""db7d0187-b036-4b42-9dd7-ab618a1a13e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch2Position"",
                    ""type"": ""Value"",
                    ""id"": ""69a93738-7988-492d-aee3-813513fad189"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1Press"",
                    ""type"": ""Button"",
                    ""id"": ""86fdf3ae-2b73-4451-a0ea-e44a759115ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch2Press"",
                    ""type"": ""Button"",
                    ""id"": ""4d7cf9a9-1987-4413-a5c6-79b55c4d5490"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ce37cee0-3fee-470f-b68f-d2f57535eb05"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""442e3399-790f-46f1-84c3-c15509b47cac"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93482bb4-5a0b-4985-8585-6182befe3153"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5ba651c-40ca-44ba-ab7c-45b223c7446d"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9212e8c4-1c08-4fff-95c1-7ac30d0c6293"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b6e302-70fc-4668-b9af-51803c1edf9f"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd560f7-775b-4703-ac97-0b65d23a6299"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62ec8d1b-5b63-4a5e-9a99-dfea4cebd831"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09eaf8e1-7e83-452a-b443-04ebd8cc997f"",
                    ""path"": ""<Touchscreen>/touch1/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Ring"",
            ""id"": ""982be9de-2fc3-4ab5-868b-3e53b23ec25b"",
            ""actions"": [
                {
                    ""name"": ""XRPose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""33cefc00-2bd8-42c4-8414-5be7577e6822"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPadClick"",
                    ""type"": ""Button"",
                    ""id"": ""a82eefa0-23f6-4b3c-831d-36615c5f673c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyClick"",
                    ""type"": ""Button"",
                    ""id"": ""26ede634-498a-4303-8dbe-764200305db4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6d4e4618-1ba6-4cde-958a-2be467a89265"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""75c5dd53-87a8-4afd-883f-102a8d83b423"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89321d41-b63a-47a8-b787-a665f09e5785"",
                    ""path"": ""<RayNeoRingController>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XRPose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74d8e7b8-419c-46dc-b6d1-7dcf9ac5386a"",
                    ""path"": ""<RingInputDevice>/button_touch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPadClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""817dae67-749c-4909-9f49-d61b1b565677"",
                    ""path"": ""<RingInputDevice>/button_heavy"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0bc7fbf-75a0-4244-9fb8-ac89f17a727e"",
                    ""path"": ""<RayNeoRingController>/homeButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29aad5e-5708-4e16-8329-1999fed88b28"",
                    ""path"": ""<RingInputDevice>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82ad01de-e7ce-4a55-869c-2ed650c19c01"",
                    ""path"": ""<RingInputDevice>/touchPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CellPhone"",
            ""id"": ""c19b0352-7d2b-403d-ab29-7bbfdcfc782e"",
            ""actions"": [
                {
                    ""name"": ""Pose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b148c107-5c45-444b-a1df-d9e3506ec2ef"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""504a76bb-c72a-4156-8723-909fe8312086"",
                    ""path"": ""<RayNeoCellPhoneController>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SimpleTouch
        m_SimpleTouch = asset.FindActionMap("SimpleTouch", throwIfNotFound: true);
        m_SimpleTouch_Tap = m_SimpleTouch.FindAction("Tap", throwIfNotFound: true);
        m_SimpleTouch_Position = m_SimpleTouch.FindAction("Position", throwIfNotFound: true);
        m_SimpleTouch_Press = m_SimpleTouch.FindAction("Press", throwIfNotFound: true);
        // MulitTouch
        m_MulitTouch = asset.FindActionMap("MulitTouch", throwIfNotFound: true);
        m_MulitTouch_Touch1Tap = m_MulitTouch.FindAction("Touch1Tap", throwIfNotFound: true);
        m_MulitTouch_Touch2Tap = m_MulitTouch.FindAction("Touch2Tap", throwIfNotFound: true);
        m_MulitTouch_Touch1Position = m_MulitTouch.FindAction("Touch1Position", throwIfNotFound: true);
        m_MulitTouch_Touch2Position = m_MulitTouch.FindAction("Touch2Position", throwIfNotFound: true);
        m_MulitTouch_Touch1Press = m_MulitTouch.FindAction("Touch1Press", throwIfNotFound: true);
        m_MulitTouch_Touch2Press = m_MulitTouch.FindAction("Touch2Press", throwIfNotFound: true);
        // Ring
        m_Ring = asset.FindActionMap("Ring", throwIfNotFound: true);
        m_Ring_XRPose = m_Ring.FindAction("XRPose", throwIfNotFound: true);
        m_Ring_TouchPadClick = m_Ring.FindAction("TouchPadClick", throwIfNotFound: true);
        m_Ring_HeavyClick = m_Ring.FindAction("HeavyClick", throwIfNotFound: true);
        m_Ring_Rotation = m_Ring.FindAction("Rotation", throwIfNotFound: true);
        m_Ring_Position = m_Ring.FindAction("Position", throwIfNotFound: true);
        // CellPhone
        m_CellPhone = asset.FindActionMap("CellPhone", throwIfNotFound: true);
        m_CellPhone_Pose = m_CellPhone.FindAction("Pose", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SimpleTouch
    private readonly InputActionMap m_SimpleTouch;
    private ISimpleTouchActions m_SimpleTouchActionsCallbackInterface;
    private readonly InputAction m_SimpleTouch_Tap;
    private readonly InputAction m_SimpleTouch_Position;
    private readonly InputAction m_SimpleTouch_Press;
    public struct SimpleTouchActions
    {
        private @RayNeoInput m_Wrapper;
        public SimpleTouchActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_SimpleTouch_Tap;
        public InputAction @Position => m_Wrapper.m_SimpleTouch_Position;
        public InputAction @Press => m_Wrapper.m_SimpleTouch_Press;
        public InputActionMap Get() { return m_Wrapper.m_SimpleTouch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SimpleTouchActions set) { return set.Get(); }
        public void SetCallbacks(ISimpleTouchActions instance)
        {
            if (m_Wrapper.m_SimpleTouchActionsCallbackInterface != null)
            {
                @Tap.started -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnTap;
                @Tap.performed -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnTap;
                @Tap.canceled -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnTap;
                @Position.started -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPosition;
                @Press.started -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPress;
                @Press.performed -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPress;
                @Press.canceled -= m_Wrapper.m_SimpleTouchActionsCallbackInterface.OnPress;
            }
            m_Wrapper.m_SimpleTouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Tap.started += instance.OnTap;
                @Tap.performed += instance.OnTap;
                @Tap.canceled += instance.OnTap;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
            }
        }
    }
    public SimpleTouchActions @SimpleTouch => new SimpleTouchActions(this);

    // MulitTouch
    private readonly InputActionMap m_MulitTouch;
    private IMulitTouchActions m_MulitTouchActionsCallbackInterface;
    private readonly InputAction m_MulitTouch_Touch1Tap;
    private readonly InputAction m_MulitTouch_Touch2Tap;
    private readonly InputAction m_MulitTouch_Touch1Position;
    private readonly InputAction m_MulitTouch_Touch2Position;
    private readonly InputAction m_MulitTouch_Touch1Press;
    private readonly InputAction m_MulitTouch_Touch2Press;
    public struct MulitTouchActions
    {
        private @RayNeoInput m_Wrapper;
        public MulitTouchActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch1Tap => m_Wrapper.m_MulitTouch_Touch1Tap;
        public InputAction @Touch2Tap => m_Wrapper.m_MulitTouch_Touch2Tap;
        public InputAction @Touch1Position => m_Wrapper.m_MulitTouch_Touch1Position;
        public InputAction @Touch2Position => m_Wrapper.m_MulitTouch_Touch2Position;
        public InputAction @Touch1Press => m_Wrapper.m_MulitTouch_Touch1Press;
        public InputAction @Touch2Press => m_Wrapper.m_MulitTouch_Touch2Press;
        public InputActionMap Get() { return m_Wrapper.m_MulitTouch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MulitTouchActions set) { return set.Get(); }
        public void SetCallbacks(IMulitTouchActions instance)
        {
            if (m_Wrapper.m_MulitTouchActionsCallbackInterface != null)
            {
                @Touch1Tap.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Tap;
                @Touch1Tap.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Tap;
                @Touch1Tap.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Tap;
                @Touch2Tap.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Tap;
                @Touch2Tap.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Tap;
                @Touch2Tap.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Tap;
                @Touch1Position.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Position;
                @Touch1Position.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Position;
                @Touch1Position.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Position;
                @Touch2Position.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Position;
                @Touch2Position.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Position;
                @Touch2Position.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Position;
                @Touch1Press.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Press;
                @Touch1Press.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Press;
                @Touch1Press.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch1Press;
                @Touch2Press.started -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Press;
                @Touch2Press.performed -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Press;
                @Touch2Press.canceled -= m_Wrapper.m_MulitTouchActionsCallbackInterface.OnTouch2Press;
            }
            m_Wrapper.m_MulitTouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Touch1Tap.started += instance.OnTouch1Tap;
                @Touch1Tap.performed += instance.OnTouch1Tap;
                @Touch1Tap.canceled += instance.OnTouch1Tap;
                @Touch2Tap.started += instance.OnTouch2Tap;
                @Touch2Tap.performed += instance.OnTouch2Tap;
                @Touch2Tap.canceled += instance.OnTouch2Tap;
                @Touch1Position.started += instance.OnTouch1Position;
                @Touch1Position.performed += instance.OnTouch1Position;
                @Touch1Position.canceled += instance.OnTouch1Position;
                @Touch2Position.started += instance.OnTouch2Position;
                @Touch2Position.performed += instance.OnTouch2Position;
                @Touch2Position.canceled += instance.OnTouch2Position;
                @Touch1Press.started += instance.OnTouch1Press;
                @Touch1Press.performed += instance.OnTouch1Press;
                @Touch1Press.canceled += instance.OnTouch1Press;
                @Touch2Press.started += instance.OnTouch2Press;
                @Touch2Press.performed += instance.OnTouch2Press;
                @Touch2Press.canceled += instance.OnTouch2Press;
            }
        }
    }
    public MulitTouchActions @MulitTouch => new MulitTouchActions(this);

    // Ring
    private readonly InputActionMap m_Ring;
    private IRingActions m_RingActionsCallbackInterface;
    private readonly InputAction m_Ring_XRPose;
    private readonly InputAction m_Ring_TouchPadClick;
    private readonly InputAction m_Ring_HeavyClick;
    private readonly InputAction m_Ring_Rotation;
    private readonly InputAction m_Ring_Position;
    public struct RingActions
    {
        private @RayNeoInput m_Wrapper;
        public RingActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @XRPose => m_Wrapper.m_Ring_XRPose;
        public InputAction @TouchPadClick => m_Wrapper.m_Ring_TouchPadClick;
        public InputAction @HeavyClick => m_Wrapper.m_Ring_HeavyClick;
        public InputAction @Rotation => m_Wrapper.m_Ring_Rotation;
        public InputAction @Position => m_Wrapper.m_Ring_Position;
        public InputActionMap Get() { return m_Wrapper.m_Ring; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RingActions set) { return set.Get(); }
        public void SetCallbacks(IRingActions instance)
        {
            if (m_Wrapper.m_RingActionsCallbackInterface != null)
            {
                @XRPose.started -= m_Wrapper.m_RingActionsCallbackInterface.OnXRPose;
                @XRPose.performed -= m_Wrapper.m_RingActionsCallbackInterface.OnXRPose;
                @XRPose.canceled -= m_Wrapper.m_RingActionsCallbackInterface.OnXRPose;
                @TouchPadClick.started -= m_Wrapper.m_RingActionsCallbackInterface.OnTouchPadClick;
                @TouchPadClick.performed -= m_Wrapper.m_RingActionsCallbackInterface.OnTouchPadClick;
                @TouchPadClick.canceled -= m_Wrapper.m_RingActionsCallbackInterface.OnTouchPadClick;
                @HeavyClick.started -= m_Wrapper.m_RingActionsCallbackInterface.OnHeavyClick;
                @HeavyClick.performed -= m_Wrapper.m_RingActionsCallbackInterface.OnHeavyClick;
                @HeavyClick.canceled -= m_Wrapper.m_RingActionsCallbackInterface.OnHeavyClick;
                @Rotation.started -= m_Wrapper.m_RingActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_RingActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_RingActionsCallbackInterface.OnRotation;
                @Position.started -= m_Wrapper.m_RingActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_RingActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_RingActionsCallbackInterface.OnPosition;
            }
            m_Wrapper.m_RingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @XRPose.started += instance.OnXRPose;
                @XRPose.performed += instance.OnXRPose;
                @XRPose.canceled += instance.OnXRPose;
                @TouchPadClick.started += instance.OnTouchPadClick;
                @TouchPadClick.performed += instance.OnTouchPadClick;
                @TouchPadClick.canceled += instance.OnTouchPadClick;
                @HeavyClick.started += instance.OnHeavyClick;
                @HeavyClick.performed += instance.OnHeavyClick;
                @HeavyClick.canceled += instance.OnHeavyClick;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
            }
        }
    }
    public RingActions @Ring => new RingActions(this);

    // CellPhone
    private readonly InputActionMap m_CellPhone;
    private ICellPhoneActions m_CellPhoneActionsCallbackInterface;
    private readonly InputAction m_CellPhone_Pose;
    public struct CellPhoneActions
    {
        private @RayNeoInput m_Wrapper;
        public CellPhoneActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pose => m_Wrapper.m_CellPhone_Pose;
        public InputActionMap Get() { return m_Wrapper.m_CellPhone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CellPhoneActions set) { return set.Get(); }
        public void SetCallbacks(ICellPhoneActions instance)
        {
            if (m_Wrapper.m_CellPhoneActionsCallbackInterface != null)
            {
                @Pose.started -= m_Wrapper.m_CellPhoneActionsCallbackInterface.OnPose;
                @Pose.performed -= m_Wrapper.m_CellPhoneActionsCallbackInterface.OnPose;
                @Pose.canceled -= m_Wrapper.m_CellPhoneActionsCallbackInterface.OnPose;
            }
            m_Wrapper.m_CellPhoneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pose.started += instance.OnPose;
                @Pose.performed += instance.OnPose;
                @Pose.canceled += instance.OnPose;
            }
        }
    }
    public CellPhoneActions @CellPhone => new CellPhoneActions(this);
    public interface ISimpleTouchActions
    {
        void OnTap(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
        void OnPress(InputAction.CallbackContext context);
    }
    public interface IMulitTouchActions
    {
        void OnTouch1Tap(InputAction.CallbackContext context);
        void OnTouch2Tap(InputAction.CallbackContext context);
        void OnTouch1Position(InputAction.CallbackContext context);
        void OnTouch2Position(InputAction.CallbackContext context);
        void OnTouch1Press(InputAction.CallbackContext context);
        void OnTouch2Press(InputAction.CallbackContext context);
    }
    public interface IRingActions
    {
        void OnXRPose(InputAction.CallbackContext context);
        void OnTouchPadClick(InputAction.CallbackContext context);
        void OnHeavyClick(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
    }
    public interface ICellPhoneActions
    {
        void OnPose(InputAction.CallbackContext context);
    }
}
